"""Constants for Android Device Control."""

DOMAIN = "android_device_control"

ATTR_DEVICE_ID = "device_id"

SERVICE_SET_RINGER_MODE = "set_ringer_mode"
SERVICE_SET_VOLUME = "set_volume"
SERVICE_SET_DO_NOT_DISTURB = "set_do_not_disturb"
SERVICE_MEDIA_CONTROL = "media_control"
SERVICE_STOP_TTS = "stop_tts"
SERVICE_TURN_SCREEN_ON = "turn_screen_on"
SERVICE_SET_SCREEN_BRIGHTNESS = "set_screen_brightness"
SERVICE_SET_AUTO_BRIGHTNESS = "set_auto_brightness"
SERVICE_SET_SCREEN_TIMEOUT = "set_screen_timeout"
SERVICE_OPEN_WEBVIEW = "open_webview"
SERVICE_SET_FLASHLIGHT = "set_flashlight"
SERVICE_SET_BLUETOOTH = "set_bluetooth"
SERVICE_SET_BLE_TRANSMITTER = "set_ble_transmitter"
SERVICE_CONFIGURE_BLE_TRANSMITTER = "configure_ble_transmitter"
SERVICE_SET_BEACON_MONITOR = "set_beacon_monitor"
SERVICE_REQUEST_LOCATION_UPDATE = "request_location_update"
SERVICE_UPDATE_SENSORS = "update_sensors"
SERVICE_SET_HIGH_ACCURACY_MODE = "set_high_accuracy_mode"
SERVICE_SET_HIGH_ACCURACY_INTERVAL = "set_high_accuracy_interval"
SERVICE_LAUNCH_APP = "launch_app"
SERVICE_LAUNCH_ACTIVITY = "launch_activity"
SERVICE_SET_APP_LOCK = "set_app_lock"
SERVICE_SET_WAKE_WORD_DETECTION = "set_wake_word_detection"
SERVICE_SET_PERSISTENT_CONNECTION = "set_persistent_connection"
SERVICE_SEND_BROADCAST_INTENT = "send_broadcast_intent"
SERVICE_CLEAR_NOTIFICATION = "clear_notification"
SERVICE_REMOVE_NOTIFICATION_CHANNEL = "remove_notification_channel"
SERVICE_KIOSK_SHOW_SCREENSAVER = "kiosk_show_screensaver"
SERVICE_KIOSK_HIDE_SCREENSAVER = "kiosk_hide_screensaver"
SERVICE_KIOSK_SHOW_CAMERA = "kiosk_show_camera"
SERVICE_KIOSK_HIDE_CAMERA = "kiosk_hide_camera"
SERVICE_KIOSK_SET_BRIGHTNESS = "kiosk_set_brightness"
SERVICE_KIOSK_SET_VOLUME = "kiosk_set_volume"
SERVICE_KIOSK_RELOAD = "kiosk_reload"
SERVICE_KIOSK_DEFAULT = "kiosk_default"
SERVICE_SEND_COMMAND = "send_command"
