name: Test

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  test:
    name: Test (minimum Home Assistant)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: pip
      - run: python -m pip install -r requirements_test.txt
      - run: python scripts/set_release_version.py --check
      - run: ruff format --check .
      - run: ruff check .
      - run: pytest

  current-home-assistant:
    name: Test (current Home Assistant)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: pip
      - run: python -m pip install -r requirements_test.txt
      - name: Upgrade Home Assistant to current stable
        run: python -m pip install --upgrade homeassistant
      - run: pytest
